In [372]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [373]:
# Load iris data
iris = load_iris()

In [374]:
X = iris.data
y = iris.target # classes labels

In [375]:
# Load the iris dataset
copy_iris = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add a new column named 'original_class' and copy the target value
copy_iris['original_class'] = y

print(copy_iris)

# Print the modified DataFrame
print(copy_iris['original_class'])

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     original_class  
0    

In [376]:
print(X)
X_with_ones = np.c_[np.ones(copy_iris.shape[0]), copy_iris] # Add ones to the training data
print(X_with_ones)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [377]:
print(y)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [378]:
# Combine C2 and C3 to class 2
y_new23 = np.where(y == 0, 1, -1)
print(y_new23)


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1]


In [379]:
# Combine C1 and C2 to class 1
y_new12 = np.where(y == 2, 1, -1)
print(y_new12)


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1]


In [380]:
# Combine C1 and C3 to class 2
y_new13 = np.where(y == 1, 1, -1)
print(y_new13)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1]


In [381]:
def get_original_lables(test_final):
  original_lables = []
  for i in range(0, len(test_final)):
    original_lables.append(test_final[i][5])

  return original_lables

In [382]:
def delete_last_column(data):
  return data[:, :-1]  # Select all rows and all columns except the last

In [383]:
def split_dataset(X_updated, Y_updated):
  # Split data into training and test sets

  # Further split class 1 for training and testing (40 train, 10 test)
  X_train_C1, X_test_C1, y_train_C1, y_test_C1 = train_test_split(X_updated[Y_updated == 1], Y_updated[Y_updated == 1], test_size=0.2, random_state=42)
  print("1st Class Dimensionalities")

  print("Training samples shape ", X_train_C1.shape)
  print("Testing samples shape ", X_test_C1.shape)
  print("Training lables shape ", y_train_C1.shape)
  print("Testing lables shape ", y_test_C1.shape)

  # Further split class 1 for training and testing (80 train, 20 test)
  X_train_C2, X_test_C2, y_train_C2, y_test_C2 = train_test_split(X_updated[Y_updated == -1], Y_updated[Y_updated == -1], test_size=0.2, random_state=42)

  print("================================")

  print("1st Class Dimensionalities")
  print("Training samples shape ", X_train_C2.shape)
  print("Testing samples shape ", X_test_C2.shape)
  print("Training lables shape ", y_train_C2.shape)
  print("Testing lables shape ", y_test_C2.shape)


  # Combine training data for C1 and C2
  X_train_final = np.concatenate((X_train_C1, X_train_C2))
  y_train_final = np.concatenate((y_train_C1, y_train_C2))


  # Combine testing data for C1 and C2
  X_test_final = np.concatenate((X_test_C1, X_test_C2))
  y_test_final = np.concatenate((y_test_C1, y_test_C2))

  return X_train_final, y_train_final, X_test_final, y_test_final


In [384]:
def calculate_best_fit_weight(X_train, y_train):
  best_fit_weight = np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train
  print(best_fit_weight)
  return best_fit_weight

In [385]:
# Divide the data into 2 categories class 1 and 2&3
x_train1, y_train1, x_test1, y_test1 = split_dataset(X_with_ones, y_new23)
# best_fit_weight1 = calculate_best_fit_weight(x_train1, y_train1)


1st Class Dimensionalities
Training samples shape  (40, 6)
Testing samples shape  (10, 6)
Training lables shape  (40,)
Testing lables shape  (10,)
1st Class Dimensionalities
Training samples shape  (80, 6)
Testing samples shape  (20, 6)
Training lables shape  (80,)
Testing lables shape  (20,)


In [386]:
# Divide the data into 2 categories class 2 and 1&3
x_train2, y_train2, x_test2, y_test2 = split_dataset(X_with_ones, y_new13)
# best_fit_weight2 = calculate_best_fit_weight(x_train2, y_train2)

1st Class Dimensionalities
Training samples shape  (40, 6)
Testing samples shape  (10, 6)
Training lables shape  (40,)
Testing lables shape  (10,)
1st Class Dimensionalities
Training samples shape  (80, 6)
Testing samples shape  (20, 6)
Training lables shape  (80,)
Testing lables shape  (20,)


In [387]:
# Divide the data into 2 categories class 3 and 1&2
x_train3, y_train3, x_test3, y_test3 = split_dataset(X_with_ones, y_new12)
# best_fit_weight3 = calculate_best_fit_weight(x_train3, y_train3)

1st Class Dimensionalities
Training samples shape  (40, 6)
Testing samples shape  (10, 6)
Training lables shape  (40,)
Testing lables shape  (10,)
1st Class Dimensionalities
Training samples shape  (80, 6)
Testing samples shape  (20, 6)
Training lables shape  (80,)
Testing lables shape  (20,)


In [388]:
def get_original_lables(test_final):
  original_lables = []
  for i in range(0, len(test_final)):
    original_lables.append(test_final[i][5])

  return original_lables

In [389]:
# Combine the testing sample
X_test_final = np.concatenate((x_test1, x_test2))
X_test_final = np.concatenate((X_test_final, x_test3))

y_test_final = np.concatenate((y_test1, y_test2))
y_test_final = np.concatenate((y_test_final, y_test3))

print(X_test_final)
print("==================")
print(y_test_final)
print("==================")

y_test_original_lables = get_original_lables(X_test_final)
print(y_test_original_lables)

print(y_test_final.shape)
print(X_test_final.shape)

[[1.  4.3 3.  1.1 0.1 0. ]
 [1.  5.1 3.4 1.5 0.2 0. ]
 [1.  4.8 3.1 1.6 0.2 0. ]
 [1.  4.8 3.  1.4 0.3 0. ]
 [1.  5.1 3.5 1.4 0.3 0. ]
 [1.  5.3 3.7 1.5 0.2 0. ]
 [1.  5.  3.4 1.6 0.4 0. ]
 [1.  5.  3.  1.6 0.2 0. ]
 [1.  5.2 4.1 1.5 0.1 0. ]
 [1.  5.1 3.8 1.5 0.3 0. ]
 [1.  6.3 2.8 5.1 1.5 2. ]
 [1.  6.3 2.9 5.6 1.8 2. ]
 [1.  6.9 3.2 5.7 2.3 2. ]
 [1.  5.7 3.  4.2 1.2 1. ]
 [1.  5.6 2.7 4.2 1.3 1. ]
 [1.  5.5 2.5 4.  1.3 1. ]
 [1.  6.3 2.5 4.9 1.5 1. ]
 [1.  7.4 2.8 6.1 1.9 2. ]
 [1.  5.  2.  3.5 1.  1. ]
 [1.  7.  3.2 4.7 1.4 1. ]
 [1.  6.2 2.2 4.5 1.5 1. ]
 [1.  5.5 2.4 3.8 1.1 1. ]
 [1.  6.3 2.7 4.9 1.8 2. ]
 [1.  6.  2.7 5.1 1.6 1. ]
 [1.  6.7 3.1 5.6 2.4 2. ]
 [1.  6.5 2.8 4.6 1.5 1. ]
 [1.  6.2 2.8 4.8 1.8 2. ]
 [1.  6.1 3.  4.9 1.8 2. ]
 [1.  6.  2.2 4.  1.  1. ]
 [1.  5.5 2.4 3.7 1.  1. ]
 [1.  6.1 2.9 4.7 1.4 1. ]
 [1.  5.5 2.5 4.  1.3 1. ]
 [1.  5.5 2.4 3.8 1.1 1. ]
 [1.  5.7 3.  4.2 1.2 1. ]
 [1.  5.8 2.7 4.1 1.  1. ]
 [1.  5.1 2.5 3.  1.1 1. ]
 [1.  6.8 2.8 4.8 1.4 1. ]
 

In [390]:
# Delete the Last column that contains the original lables we've added to handle Dimensionality
x_train1 = delete_last_column(x_train1.copy())
x_test1 = delete_last_column(x_test1.copy())

print(x_train1.shape)
print(x_test1.shape)

# Delete the Last column that contains the original lables we've added to handle Dimensionality
x_train2 = delete_last_column(x_train2.copy())
x_test2 = delete_last_column(x_test2.copy())

print(x_train2.shape)
print(x_test2.shape)

# Delete the Last column that contains the original lables we've added to handle Dimensionality
x_train3 = delete_last_column(x_train3.copy())
x_test3 = delete_last_column(x_test3.copy())


print(x_train3.shape)
print(x_test3.shape)

# Delete the Last column that contains the original lables we've added to handle Dimensionality
X_test_final = delete_last_column(X_test_final.copy())
print(X_test_final.shape)


(120, 5)
(30, 5)
(120, 5)
(30, 5)
(120, 5)
(30, 5)
(90, 5)


In [391]:
best_fit_weight1 = calculate_best_fit_weight(x_train1, y_train1)
best_fit_weight2 = calculate_best_fit_weight(x_train2, y_train2)
best_fit_weight3 = calculate_best_fit_weight(x_train3, y_train3)

[-0.72396059  0.12016826  0.47807312 -0.41859655 -0.16621896]
[ 1.89367432 -0.03356287 -0.81703486  0.41856341 -0.92296516]
[-2.33177666 -0.20426706  0.5070871   0.12267199  0.97601947]


In [392]:
def decide_class(line1, line2, line3, test_sample):
  sample_sign_list =[]

  line1_sign = np.sign(np.dot(test_sample, line1))
  line2_sign = np.sign(np.dot(test_sample, line2))
  line3_sign = np.sign(np.dot(test_sample, line3))

  sample_sign_list.append(line1_sign)
  sample_sign_list.append(line2_sign)
  sample_sign_list.append(line3_sign)

  positive_indices = []
  negative_indices = []
  for i, num in enumerate(sample_sign_list):
    if num > 0:
      positive_indices.append(i)
    if num < 0:
      negative_indices.append(i)

  print(test_sample)
  print(positive_indices)
  print(negative_indices)

  return positive_indices


In [393]:
def calculate_accuracy(actual, counter):
  accuracy = counter/ len(actual) * 100

  print("The accuracy of this model is ", accuracy)

In [394]:
counter = 0
for i, test_sample in enumerate(X_test_final):
    predicted_class = decide_class(best_fit_weight1, best_fit_weight2, best_fit_weight3, test_sample)
    actual_class_label = y_test_original_lables[i]  # Access the corresponding actual class label

    print("Actual class label:", actual_class_label)
    print("Predicted class label:", predicted_class)
    if actual_class_label in predicted_class:
      counter += 1


    print("================================")

print(X_test_final.shape)
print(y.shape)

calculate_accuracy(y_test_original_lables, counter)

[1.  4.3 3.  1.1 0.1]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.1 3.4 1.5 0.2]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  4.8 3.1 1.6 0.2]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  4.8 3.  1.4 0.3]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.1 3.5 1.4 0.3]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.3 3.7 1.5 0.2]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.  3.4 1.6 0.4]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.  3.  1.6 0.2]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.2 4.1 1.5 0.1]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  5.1 3.8 1.5 0.3]
[0]
[1, 2]
Actual class label: 0.0
Predicted class label: [0]
[1.  6.3 2.8 5.1 1.5]
[1]
[0, 2]
Actual class label: 2.0
Predicted class label: [1]
[1.  6.3 2.9 5.6 1.8]
[2]
[0, 1]
Actual class label: 2.0
Predicted class lab